### ISSUE TITLE
Are MRR numbers of tgbl-wiki and tgbl-review reported in your paper correct?

### ISSUE THREAD

**Issue by zxhxgithub** [shenyangHuang/TGB#62]
Hi,
I wonder if the mrr numbers of dataset `tgbl-wiki` and `tgbl-review` reported in your paper correct, or if there is something wrong with these dataset.
I ran the command according to the `examples/linkproppred/tgbl-wiki/tgn.py`, and got the mrr number about 0.31, much lower than the reported number about 0.73. And similarly in `tgbl-review`, I got 0.32 on validation data and 0.37 on test data, rather than 0.46 and 0.53 reported.
By the way, are the `LinkPredictor` and `criterion`  in `tgn.py` matching correctly? In `/modules/decoders.py`, the `LinkPredictor` contains a `sigmoid` function after `lin_final(h)`. However, in `tgn.py` line 265, `criterion` is `BCEWithLogitsLoss()`. I also refer to https://github.com/pyg-team/pytorch_geometric/blob/master/examples/tgn.py line 75 and line 111, finding that there is no `sigmoid` in the `LinkPredictor`. Should this `sigmoid` function be removed?
Looking forward to your reply!

**Comment by shenyangHuang** [comment]
Hi,

Thanks for your interest in our work and thanks for reaching out. 

I believe the version of the paper you are looking at is an earlier preprint version, see the [updated arxiv version](https://arxiv.org/pdf/2307.01026.pdf). The difference in TGN performance for example is because in `tgbl-wiki-v2` and `tgbl-review-v2` we increased the number of negative sample per positive edge significantly thus resulting in reduced performance of various model (interestingly different models are affected differently). `tgbl-wiki-v1` and `tgbl-review-v1` results with 20 negative samples can now be found in Appendix H of the paper. 

For the second questions, the `BCEWithLogitsLoss()` is a combined class of one `sigmoid` layer and  `BCELoss` thus there is no need to apply the `sigmoid` at the final layer as it will be applied when computing the loss. 

Hope it answers your questions. 

Best,
Shenyang(Andy) Huang
