### ISSUE TITLE
Extra sigmoid() in LinkPredictor output leads to wrong results on the leaderboard

### ISSUE THREAD

**Issue by fsabau** [shenyangHuang/TGB#83]
The `LinkPredictor` from `modules/decoder.py` has a `.sigmoid()` call on the output, but the implementations from `examples/linkproppred` for TGN and DyRep use `BCEWithLogitsLoss` which also includes a sigmoid call before computing the loss. This leads to `sigmoid` being applied twice.

To see if this affects the results, I ran some experiments using `python examples/linkproppred/tgbl-wiki/tgn.py --data "tgbl-wiki" --num_run 1 --seed 1`. Just by removing the extra `sigmoid()` I got 0.58 val MRR and 0.52 val MRR, which is already higher than what is reported on the official leaderboard. By also setting the batch size to 16 (`--bs 16`) I got 0.70 val MRR and 0.65 test MRR, which would put TGN in 4th place on the tgbl-wiki-v2 leaderboard.

Unfortunately it does look like the TGN and DyRep results on the link property prediction tasks will need to be recomputed again after the issue is fixed.

**Comment by shenyangHuang** [comment]
Hi, 

Thanks for raising this point. 
The results on the TGB leaderboard is repeated across 5 random seeds, thus comparing the results from 5 random seeds would be more comparable. It is possible that `sigmoid()` might have some effect, we can examine it with the average across 5 seeds. 

In terms of batch size, due to models such as TGN update its memory after each batch, it is more comparable when they all use the same batch size. Smaller batch size means more frequent memory update thus giving the model more information for prediction (which can explain the performance difference). 

Best,
Andy
